### ISSUE TITLE
Players cannot move when using some GeoJSON points

### ISSUE THREAD

**Issue by tululum** [BilelJegham/Geoguess-2#17]
Hi,

I've encountered a rather rare but a bit game-breaking issue. When I played using GeoJSON with my friends and family, sometimes it happened so that the person who set up the room could play normally but all the other players were locked in place, unable to move. For some reason, different street view spots were chosen for room owner and other players (and the other players were placed into static panorama view without the possibility to move). Luckily, I recall one such spot that reliably has this issue every time, so that can be used to debug the issue.

**How to replicate:**

1. Use following GeoJSON:

```
{"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"EPSG:4326"}},"features":[{"type":"Feature","id":15,"geometry":{"type":"Point","coordinates":[12.754708932182819,50.187283464784805]},"properties":{"OBJECTID":15,"JMENO":"Loket","NATOCENI":0,"DATA50_K":"1450000","DATA50_P":"hrad"}}]}
```

2. Start a multiplayer game (starting the second instance in anonymous browser mode is sufficient).
3. First player (room owner) can move. Second player (and 3rd, 4th, ...) cannot move.

If you could take a look at this that would be great!

**Comment by BilelJegham** [comment]
Hi, sorry for the delay.

The position is close to street view street and photosphere. The problem comes from this. I will fix that soon.

![image](https://user-images.githubusercontent.com/20130405/90337503-3bad3a00-dfe3-11ea-8e96-60cacd60b3f7.png)

**Comment by BilelJegham** [comment]
@tululum Bug fix and deploy on https://geoguess2.netlify.app/

Thanks for your feedback
